ERROR 2023-09-25 03:35:14,109 exception Invalid HTTP_HOST header: 'ec2-54-206-144-94.ap-southeast-2.compute.amazonaws.com'. You may need to add 'ec2-54-206-144-94.ap-southeast-2.compute.amazonaws.com' to ALLOWED_HOSTS.
WARNING 2023-09-25 03:35:14,114 log Bad Request: /.env
ERROR 2023-09-25 03:35:17,618 exception Invalid HTTP_HOST header: 'ec2-54-206-144-94.ap-southeast-2.compute.amazonaws.com'. You may need to add 'ec2-54-206-144-94.ap-southeast-2.compute.amazonaws.com' to ALLOWED_HOSTS.
WARNING 2023-09-25 03:35:17,621 log Bad Request: /
WARNING 2023-09-25 04:23:06,155 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-25 04:50:30,558 log Forbidden (Referer checking failed - no Referer.): /inquiry_details/
WARNING 2023-09-25 04:50:31,245 log Forbidden (Referer checking failed - no Referer.): /inquiry_details/
WARNING 2023-09-25 04:50:31,932 log Forbidden (Referer checking failed - no Referer.): /inquiry_details/
WARNING 2023-09-25 04:50:32,818 log Forbidden (Referer checking failed - no Referer.): /inquiry_details2/
WARNING 2023-09-25 04:50:33,260 log Forbidden (Referer checking failed - no Referer.): /inquiry_details2/
WARNING 2023-09-25 04:50:33,703 log Forbidden (Referer checking failed - no Referer.): /inquiry_details2/
WARNING 2023-09-25 04:50:35,397 log Forbidden (Referer checking failed - no Referer.): /inquiry_details1/
WARNING 2023-09-25 04:50:35,862 log Forbidden (Referer checking failed - no Referer.): /inquiry_details1/
WARNING 2023-09-25 04:50:36,302 log Forbidden (Referer checking failed - no Referer.): /inquiry_details1/
WARNING 2023-09-25 04:51:02,062 log Not Found: /products/news/
WARNING 2023-09-25 04:51:02,481 log Not Found: /products/news/
WARNING 2023-09-25 04:51:03,098 log Not Found: /products/news/
WARNING 2023-09-25 04:51:03,479 log Not Found: /products/news/
WARNING 2023-09-25 04:51:03,854 log Not Found: /products/news/
WARNING 2023-09-25 04:51:04,229 log Not Found: /products/news/uni_subscribe_email=xivwajotoq@outlook.com
WARNING 2023-09-25 04:51:04,608 log Not Found: /products/news/uni_subscribe_email=xivwajotoq@outlook.com
WARNING 2023-09-25 04:51:04,991 log Not Found: /products/registry/
WARNING 2023-09-25 04:51:05,649 log Not Found: /products/registry/
WARNING 2023-09-25 04:51:06,027 log Not Found: /products/registry/
WARNING 2023-09-25 04:51:06,646 log Not Found: /products/registry/
WARNING 2023-09-25 04:51:07,019 log Not Found: /products/registry/
WARNING 2023-09-25 04:51:07,392 log Not Found: /products/registry/uni_subscribe_email=xivwajotoq@outlook.com
WARNING 2023-09-25 04:51:07,767 log Not Found: /products/registry/uni_subscribe_email=xivwajotoq@outlook.com
WARNING 2023-09-25 04:51:08,140 log Not Found: /technology/ai/
WARNING 2023-09-25 04:51:08,534 log Not Found: /technology/ai/
WARNING 2023-09-25 04:51:08,907 log Not Found: /technology/ai/
WARNING 2023-09-25 04:51:09,526 log Not Found: /technology/ai/
WARNING 2023-09-25 04:51:09,968 log Not Found: /technology/ai/
WARNING 2023-09-25 04:51:10,344 log Not Found: /technology/ai/uni_subscribe_email=xivwajotoq@outlook.com
WARNING 2023-09-25 04:51:10,717 log Not Found: /technology/ai/uni_subscribe_email=xivwajotoq@outlook.com
ERROR 2023-09-25 05:00:45,881 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-25 05:03:00,161 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-25 05:03:08,748 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-25 05:05:00,929 log Internal Server Error: /horeb_yhwh/blog/post/2176/change/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1221, in save_model
    obj.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 204, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
UnboundLocalError: local variable 'service' referenced before assignment
ERROR 2023-09-25 05:05:26,122 log Internal Server Error: /horeb_yhwh/blog/post/2176/change/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1221, in save_model
    obj.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 204, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
UnboundLocalError: local variable 'service' referenced before assignment
ERROR 2023-09-25 05:08:04,745 log Internal Server Error: /horeb_yhwh/blog/post/2176/change/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1221, in save_model
    obj.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 204, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
UnboundLocalError: local variable 'service' referenced before assignment
ERROR 2023-09-25 05:09:24,784 log Internal Server Error: /horeb_yhwh/blog/post/2176/change/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1746, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1221, in save_model
    obj.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 204, in create_event_on_calendar
    event = service.events().insert(calendarId='primary', body=event).execute()
UnboundLocalError: local variable 'service' referenced before assignment
WARNING 2023-09-25 05:23:35,365 log Not Found: /robots.txt
WARNING 2023-09-25 05:23:38,024 log Not Found: /sitemap.xml
WARNING 2023-09-25 05:29:00,813 log Not Found: /.git/config
WARNING 2023-09-25 05:32:18,745 log Not Found: /shop/product-category/uncategorised/
WARNING 2023-09-25 05:34:18,896 log Not Found: /robots.txt
WARNING 2023-09-25 05:56:33,900 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-25 06:30:16,063 log Not Found: /dns-query
WARNING 2023-09-25 06:43:54,435 log Not Found: /dns-query
WARNING 2023-09-25 06:44:59,721 log Not Found: /robots.txt
WARNING 2023-09-25 06:49:15,486 log Forbidden (Referer checking failed - no Referer.): /admin/login/
WARNING 2023-09-25 07:21:51,566 log Not Found: /apple-touch-icon-120x120-precomposed.png
WARNING 2023-09-25 07:21:51,616 log Not Found: /apple-touch-icon-120x120.png
WARNING 2023-09-25 07:29:51,615 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-25 07:31:52,878 log Not Found: /wp-login.php
WARNING 2023-09-25 07:38:01,262 log Not Found: /wp-login.php
WARNING 2023-09-25 07:51:43,736 log Not Found: /apple-touch-icon-120x120-precomposed.png
WARNING 2023-09-25 07:51:44,036 log Not Found: /apple-touch-icon-120x120.png
