WARNING 2023-09-24 03:36:12,559 log Not Found: /dns-query
WARNING 2023-09-24 03:37:04,351 log Not Found: /dns-query
WARNING 2023-09-24 03:37:04,982 log Not Found: /contact/
WARNING 2023-09-24 03:38:52,251 log Not Found: /robots.txt
WARNING 2023-09-24 03:38:53,766 log Not Found: /airport-transfers-leichhardt/
WARNING 2023-09-24 03:58:48,534 log Not Found: /shop/product/2014-new-moncler-faucon-women-down-jacket-zip-with-grey/
WARNING 2023-09-24 04:06:05,945 log Not Found: /robots.txt
WARNING 2023-09-24 04:25:53,980 log Not Found: /robots.txt
WARNING 2023-09-24 04:29:09,377 log Not Found: /robots.txt
WARNING 2023-09-24 04:40:13,512 log Not Found: /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application
WARNING 2023-09-24 05:00:38,619 log Not Found: /.env
WARNING 2023-09-24 05:00:39,792 log Forbidden (Referer checking failed - no Referer.): /
WARNING 2023-09-24 05:02:50,757 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-24 05:36:00,233 log Not Found: /robots.txt
WARNING 2023-09-24 05:43:32,495 log Not Found: /robots.txt
ERROR 2023-09-24 05:43:33,383 log Internal Server Error: /return_trip_detail/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/basecamp/views.py", line 2050, in return_trip_detail
    return render(request, 'beasecamp/return_trip.html', {})
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 102, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: beasecamp/return_trip.html
WARNING 2023-09-24 05:51:20,387 log Not Found: /shop/ko/product/moncler-clamart-8/
WARNING 2023-09-24 06:07:51,702 log Not Found: /nologin.php
WARNING 2023-09-24 06:33:26,285 log Not Found: /_profiler/phpinfo
WARNING 2023-09-24 06:33:29,277 log Not Found: /yuuki
WARNING 2023-09-24 06:33:31,224 log Not Found: /.env
WARNING 2023-09-24 06:33:33,630 log Forbidden (Referer checking failed - no Referer.): /
ERROR 2023-09-24 06:36:05,599 log Internal Server Error: /confirm_booking_detail/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/basecamp/views.py", line 1723, in confirm_booking_detail
    p.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 32, in notify_user_post
    p.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 250, in create_event_on_calendar
    creds.refresh(Request())
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/reauth.py", line 351, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/_client.py", line 73, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('deleted_client: The OAuth client was deleted.', {'error': 'deleted_client', 'error_description': 'The OAuth client was deleted.'})
WARNING 2023-09-24 06:36:18,878 log Not Found: /Core/Skin/Login.aspx
ERROR 2023-09-24 06:38:29,357 log Internal Server Error: /confirm_booking_detail/
Traceback (most recent call last):
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/ubuntu/github/easygo/basecamp/views.py", line 1723, in confirm_booking_detail
    p.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 32, in notify_user_post
    p.save()
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/signals_handlers.py", line 66, in wrapper
    return receiver(*args, **kwargs)
  File "/home/ubuntu/github/easygo/blog/signals.py", line 250, in create_event_on_calendar
    creds.refresh(Request())
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/reauth.py", line 351, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/home/ubuntu/github/easygo/venv/lib/python3.10/site-packages/google/oauth2/_client.py", line 73, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('deleted_client: The OAuth client was deleted.', {'error': 'deleted_client', 'error_description': 'The OAuth client was deleted.'})
WARNING 2023-09-24 06:44:56,124 log Not Found: /robots.txt
WARNING 2023-09-24 06:53:49,475 log Not Found: /robots.txt
WARNING 2023-09-24 06:57:26,075 log Not Found: /robots.txt
ERROR 2023-09-24 06:59:41,039 log Internal Server Error: /paypal_ipn/
WARNING 2023-09-24 07:15:19,757 log Not Found: /contact/
ERROR 2023-09-24 07:16:14,583 log Internal Server Error: /paypal_ipn/
WARNING 2023-09-24 07:28:05,204 log Forbidden (Referer checking failed - no Referer.): /admin/login/
WARNING 2023-09-24 07:31:46,957 log Not Found: /c/
WARNING 2023-09-24 07:44:13,008 log Not Found: /price-booking
WARNING 2023-09-24 08:09:31,128 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-24 08:11:42,373 log Not Found: /resetpw.php
WARNING 2023-09-24 08:11:42,876 log Not Found: /resetuser.php
WARNING 2023-09-24 08:11:43,380 log Not Found: /passcode.php
WARNING 2023-09-24 08:13:11,003 log Not Found: /shop/product/moncler-vest-men-fontaine-brown/
WARNING 2023-09-24 08:28:07,540 log Not Found: /shop/es/product/moncler-chaquetas-mujer-lievre-azul/
WARNING 2023-09-24 08:41:29,785 log Not Found: /.env
WARNING 2023-09-24 09:06:02,047 log Not Found: /apple-touch-icon-120x120-precomposed.png
WARNING 2023-09-24 09:06:02,160 log Not Found: /apple-touch-icon-120x120.png
WARNING 2023-09-24 09:14:12,729 log Not Found: /robots.txt
WARNING 2023-09-24 09:14:13,926 log Not Found: /price-booking
WARNING 2023-09-24 09:24:47,318 log Not Found: /sms: 61406883355
WARNING 2023-09-24 09:24:47,733 log Not Found: /sms: 61406883355
WARNING 2023-09-24 09:25:01,327 log Not Found: /sms: 61406883355
WARNING 2023-09-24 09:25:01,765 log Not Found: /sms: 61406883355
WARNING 2023-09-24 09:37:05,323 log Not Found: /wp-content/plugins/WordPressCore/include.php
WARNING 2023-09-24 09:42:38,932 log Not Found: /Core/Skin/Login.aspx
WARNING 2023-09-24 10:02:01,962 log Not Found: /robots.txt
ERROR 2023-09-24 10:07:26,984 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-24 10:07:34,558 log Internal Server Error: /paypal_ipn/
WARNING 2023-09-24 10:10:26,126 log Not Found: /.env
WARNING 2023-09-24 10:10:27,307 log Forbidden (Referer checking failed - no Referer.): /
WARNING 2023-09-24 10:14:48,650 log Not Found: /airport-transfers-leichhardt/
ERROR 2023-09-24 10:15:06,103 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-24 10:15:12,561 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-24 10:18:43,413 log Internal Server Error: /paypal_ipn/
ERROR 2023-09-24 10:18:50,612 log Internal Server Error: /paypal_ipn/
WARNING 2023-09-24 10:21:26,345 log Not Found: /.well-known/traffic-advice
